channels:
- handle: '@hkglobalmarket'
  name_ko: HK Global Market
  slug: hkglobalmarket
  enabled: true
  channel_id: UCWskYkV4c4S9D__rsfOl2JA
- handle: '@MK_Invest'
  name_ko: MK 인베스트
  slug: mk_invest
  enabled: true
  channel_id: UCIipmgxpUxDmPP-ma3Ahvbw
- handle: '@kpunch'
  name_ko: K펀치
  slug: kpunch
  enabled: true
  channel_id: UCOB62fKRT7b73X7tRxMuN2g
- handle: '@wallst_wars'
  name_ko: MTN 월가워즈
  slug: wallst_wars
  enabled: true
  channel_id: UCzsor4tbVidqL1N_X4VDhcQ
- handle: '@오늘부터회계사'
  name_ko: 오늘부터 회계사
  slug: today_accountant
  enabled: true
  channel_id: UClhPqabyOHBxJzMkQ7k-pxg
- handle: '@eo_korea'
  name_ko: EO Korea
  slug: eo_korea
  enabled: true
  channel_id: UCQ2DWm5Md16Dc3xRwwhVE7Q
- handle: '@DemoDaySV'
  name_ko: 데모데이
  slug: demodaysv
  enabled: true
  channel_id: UC1yWMxMin6g7wW2r_vMI38w
- handle: '@daiken_tech'
  name_ko: 다이켄 테크인사이트
  slug: daiken_tech
  enabled: true
  channel_id: UCQrjSpao4hDbEI8Y0Z9sLLw
